sudo: required
services:
  - docker

before_install:
  - docker build -t salmanfarisk/frontend -f Dockerfile.div .

script:
  - docker run salmanfarisk/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  #regoin: ""
  on: 
    branch: master