name: React-Buld-Deploy

on:
  push:
    branches : ['master']
  pull_request:
    branches : ['master']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install node js
        uses: actions/setup-node@v2
        with: 
           node-vertions: 16.x
           cache: 'npm'
      
      - name: Install npm package
        run: npm ci

      - name: Test the application
        run: npm run test

      - name: Building the application
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
      
     
